### ISSUE TITLE
Lambda does not have permission to access the ECR image. Check the ECR permissions.

### ISSUE THREAD

**Issue by GuillaumeKLECH** [aws-samples/lambda-cross-account-ecr#2]
Hello,

While following the tutorial, the lambda failed to pull image from account 1.

For it to work i had to delete the condition attached to the lambda service policy statement which is obviously not ideal.

I triple checked aws account numbers and region names, did something change since the creation of this sample ?

Are there some account specificities i have to watch for ? i'm running out of options to check any help would be appreciated i really want to avoid copying the image in another repository located in account 2.

in my configuration account 1 and 2 are not in the same organization unit and i'm using an aws sso assumed role to create the lambda, i don't know if this has anything to do with my problem...

Thanks in advance

**Comment by GuillaumeKLECH** [comment]
Sorry my mistake i should have quadruple tested the region from the lambda template...

**Comment by lmflorentino** [comment]
Hi @GuillaumeKLECH 

I gotcha the same error :(

`  An error occurred: TaskNotifierWithECRLambdaFunction - Resource handler returned message: "Lambda does not have permission to access the ECR image. Check the ECR permissions. (Service: Lambda, Status Code: 403, Request ID: 4ee4c0f1-97ca-4a19-80bb-1643686dd3d2)" (RequestToken: 80e1c7cd-0f27-6ed5-4769-3c7b7e3f160e, HandlerErrorCode: AccessDenied).`

```
    - Effect: "Allow"
      Action:
        - ecr:InitiateLayerUpload
        - ecr:SetRepositoryPolicy
        - ecr:GetRepositoryPolicy
        - ecr:GetDownloadUrlForLayer
        - ecr:BatchGetImage
        - ecr:CompleteLayerUpload
        - ecr:DescribeImages
        - ecr:DescribeRepositories
        - ecr:UploadLayerPart
        - ecr:ListImages
        - ecr:BatchCheckLayerAvailability
        - ecr:PutImage
        - ecr:GetAuthorizationToken
        - ecr:CreateRepository
        - ecr:ReplicateImage
      Resource: "arn:aws:ecr:sa-east-1:055355002851:*"
```

i already test multiples conditions on resource, all above:

```
"arn:aws:ecr:sa-east-1:055355002851:*"
"arn:aws:ecr:sa-east-1:055355002851:repository/*"
"arn:aws:ecr:sa-east-1:055355002851:repository/ops-crm"
"arn:aws:ecr:sa-east-1:055355002851:*:repository/*"
```

Anyone can help me?
