### ISSUE TITLE
Lambda does not have permission to access the ECR image. Check the ECR permissions

### ISSUE THREAD

**Issue by lmflorentino** [aws-samples/lambda-cross-account-ecr#3]
Anyone can help me? :(

i'm trying to use ECR as docker image on lambda container.

`An error occurred: TaskNotifierWithECRLambdaFunction - Resource handler returned message: "Lambda does not have permission to access the ECR image. Check the ECR permissions. (Service: Lambda, Status Code: 403, Request ID: 4ee4c0f1-97ca-4a19-80bb-1643686dd3d2)" (RequestToken: 80e1c7cd-0f27-6ed5-4769-3c7b7e3f160e, HandlerErrorCode: AccessDenied).`

**peace of my serverless.yml (iam role statements)**

```
    - Effect: "Allow"
      Action:
        - ecr:InitiateLayerUpload
        - ecr:SetRepositoryPolicy
        - ecr:GetRepositoryPolicy
        - ecr:GetDownloadUrlForLayer
        - ecr:BatchGetImage
        - ecr:CompleteLayerUpload
        - ecr:DescribeImages
        - ecr:DescribeRepositories
        - ecr:UploadLayerPart
        - ecr:ListImages
        - ecr:BatchCheckLayerAvailability
        - ecr:PutImage
        - ecr:GetAuthorizationToken
        - ecr:CreateRepository
        - ecr:ReplicateImage
      Resource: "arn:aws:ecr:sa-east-1:055355002851:*"
```

i already tested multiple conditions on resource (any not work), all below:

```
"arn:aws:ecr:sa-east-1:055355002851:*"
"arn:aws:ecr:sa-east-1:055355002851:repository/*"
"arn:aws:ecr:sa-east-1:055355002851:repository/ops-crm"
"arn:aws:ecr:sa-east-1:055355002851:*:repository/*"
```
